# Generated by Django 5.1.4 on 2025-01-20 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_key', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
    ]
