# Generated by Django 5.1.4 on 2025-01-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_key', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('product_image', models.URLField(blank=True, null=True)),
                ('delete', models.BooleanField()),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
