# Generated by Django 5.1.4 on 2025-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_remove_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
    ]
