# Generated by Django 5.1.4 on 2025-01-18 20:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='id',
            field=models.CharField(max_length=255),
        ),
    ]
