# Generated by Django 5.1.4 on 2025-01-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
