# Generated by Django 5.1.4 on 2025-01-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_production_uuid_alter_production_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delete',
        ),
    ]
